/* Auto-generated by: https://github.com/pmndrs/gltfjsx Command: npx gltfjsx@6.5.3 ginja-3.glb  */
import React, { useRef } from "react";
import { Center, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const {
    mousePosition,
    isHovering,
    isClicked,
    isDragging,
    scale = 1,
    ...otherProps
  } = props;
  const { nodes, materials } = useGLTF("/models/ginja-3.glb");
  const groupRef = useRef();
  const meshRef = useRef();

  // AUTO-ROTATION SPEED CONTROL - Change this value to adjust rotation speed
  const autoRotationSpeed = 0.35; // Different speed for each model creates variety

  useFrame((state) => {
    if (groupRef.current && meshRef.current) {
      // AUTO-ROTATION: Only rotate when not hovering
      if (!isHovering) {
        groupRef.current.rotation.y += autoRotationSpeed * 0.01; // Continuous 360° rotation
      }

      // HOVER INTERACTION: Apply hover effects when hovering but not dragging
      if (isHovering && mousePosition && !isDragging) {
        // ENHANCED HOVER INTERACTION - Much more responsive and dramatic
        const targetRotationY = mousePosition.x * 0.75;
        const targetRotationX = mousePosition.y * 0.45;

        // Faster and more responsive interpolation
        groupRef.current.rotation.y +=
          (targetRotationY - groupRef.current.rotation.y) * 0.22;
        groupRef.current.rotation.x +=
          (targetRotationX - groupRef.current.rotation.x) * 0.22;

        // Enhanced floating animation when hovering (different phase and speed)
        groupRef.current.position.y =
          Math.sin(state.clock.elapsedTime * 2.7 + 2) * 0.07;

        // More noticeable scale up when hovering - but preserve the base scale
        const targetScale = scale * 1.09;
        const currentScale = groupRef.current.scale.x;
        groupRef.current.scale.setScalar(
          currentScale + (targetScale - currentScale) * 0.16
        );
      } else if (!isHovering && !isDragging) {
        // Return to neutral position when not hovering
        groupRef.current.rotation.x += (0 - groupRef.current.rotation.x) * 0.09;
        groupRef.current.position.y += (0 - groupRef.current.position.y) * 0.09;

        // Return to original scale (which is the prop scale, not 1.0)
        const targetScale = scale;
        const currentScale = groupRef.current.scale.x;
        groupRef.current.scale.setScalar(
          currentScale + (targetScale - currentScale) * 0.09
        );
      }
    }
  });

  return (
    <group ref={groupRef} {...otherProps} dispose={null}>
      <Center>
        <mesh
          ref={meshRef}
          geometry={
            nodes["016-01_GIFO_Verpackungen_RZ_mushroom-shiitakeV2_(1)003"]
              .geometry
          }
          material={
            materials["016-01 GIFO Verpackungen_RZ_mushroom-shiitakeV2 (1).003"]
          }
          position={[0, 0, 0]} // Reset position to center
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={scale} // Apply the scale prop directly to the mesh
        />
      </Center>
    </group>
  );
}

useGLTF.preload("/models/ginja-3.glb");
