/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/outdoor-sitting.glb --output public/3D/outdoor-sitting.jsx 
*/

import React, { useRef } from "react";
import { Center, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function OutdoorSittingModel(props) {
  const { nodes, materials } = useGLTF("/3D/outdoor-sitting.glb");
  const groupRef = useRef();

  // Auto-rotation speed control
  const autoRotationSpeed = 0.35;

  useFrame(() => {
    if (groupRef.current) {
      // Continuous auto-rotation
      groupRef.current.rotation.y += autoRotationSpeed * 0.01;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <Center>
        <mesh
          geometry={nodes.polySurface933012.geometry}
          material={materials.lights}
          position={[8.482, 34.654, -12.386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933011.geometry}
          material={materials.lights}
          position={[24.34, 34.654, -12.386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933010.geometry}
          material={materials.lights}
          position={[39.737, 34.654, -12.386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933009.geometry}
          material={materials.lights}
          position={[58.809, 34.654, -12.386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933008.geometry}
          material={materials.lights}
          position={[74.667, 34.654, -12.386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933007.geometry}
          material={materials.lights}
          position={[90.064, 34.654, -12.386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933006.geometry}
          material={materials.lights}
          position={[90.217, 34.654, -88.431]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933005.geometry}
          material={materials.lights}
          position={[74.36, 34.654, -88.431]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933004.geometry}
          material={materials.lights}
          position={[58.962, 34.654, -88.431]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933003.geometry}
          material={materials.lights}
          position={[39.89, 34.654, -88.431]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933002.geometry}
          material={materials.lights}
          position={[24.033, 34.654, -88.431]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface933001.geometry}
          material={materials.lights}
          position={[8.636, 34.654, -88.431]}
          scale={25.974}
        />
        <mesh
          geometry={nodes.polySurface517003.geometry}
          material={materials.plant}
          position={[12.557, -0.009, -88.678]}
          rotation={[0, 1.16, 0]}
          scale={0.011}
        />
        <mesh
          geometry={nodes.polySurface517002.geometry}
          material={materials.plant}
          position={[91.392, -0.009, -90.227]}
          rotation={[0, -0.522, 0]}
          scale={0.011}
        />
        <mesh
          geometry={nodes.polySurface517001.geometry}
          material={materials.plant}
          position={[56.513, -0.009, -20.028]}
          scale={0.011}
        />
        <mesh
          geometry={nodes.Sofa.geometry}
          material={materials.sofa}
          position={[78.544, 0, -21.156]}
          rotation={[-Math.PI, 0.022, -Math.PI]}
          scale={0.015}
        />
        <group
          position={[23.352, 0, -50.558]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.016}
        >
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301.geometry}
            material={materials["CHAIR BODY.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_1.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_2.geometry}
            material={materials["LEATHER.001"]}
          />
        </group>
        <group
          position={[39.861, 0, -50.558]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.016}
        >
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301.geometry}
            material={materials["CHAIR BODY.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_1.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_2.geometry}
            material={materials["LEATHER.001"]}
          />
        </group>
        <group
          position={[37.247, 0, -46.682]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.016}
        >
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301.geometry}
            material={materials["CHAIR BODY.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_1.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_2.geometry}
            material={materials["LEATHER.001"]}
          />
        </group>
        <group
          position={[26.224, 0, -46.768]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.016}
        >
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301.geometry}
            material={materials["CHAIR BODY.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_1.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_2.geometry}
            material={materials["LEATHER.001"]}
          />
        </group>
        <group
          position={[37.247, 0, -54.216]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.016}
        >
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301.geometry}
            material={materials["CHAIR BODY.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_1.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_2.geometry}
            material={materials["LEATHER.001"]}
          />
        </group>
        <group
          position={[26.224, 0, -54.302]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.016}
        >
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_1.geometry}
            material={materials["LEATHER.001"]}
          />
          <mesh
            geometry={nodes.Minotti_fynn_seat_13301_2.geometry}
            material={materials["LEATHER.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Linha_top_unwrapped.geometry}
          material={materials.table}
          position={[31.655, 0, -50.558]}
        />
        <mesh
          geometry={nodes.Linha_legs.geometry}
          material={materials["table legs"]}
          position={[31.655, 0, -50.558]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials["POLE Metal"]}
          position={[50.001, -0.605, -50.627]}
          scale={[53.119, 0.208, 42.648]}
        />
        <mesh
          geometry={nodes.Cube018.geometry}
          material={materials["FLOOR.001"]}
          position={[49.944, -0.199, -7.654]}
          scale={[52.826, 0.199, 0.938]}
        />
        <mesh
          geometry={nodes.Cube014.geometry}
          material={materials["POLE Metal"]}
          position={[49.944, -0.482, -94.314]}
          rotation={[0, 1.571, 0]}
          scale={[0.213, 0.483, 52.333]}
        />
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials["POLE Metal"]}
          position={[49.944, -0.482, -6.506]}
          rotation={[0, 1.571, 0]}
          scale={[0.213, 0.483, 52.333]}
        />
        <mesh
          geometry={nodes.Cube012_unwrapped.geometry}
          material={materials["POLE Metal"]}
          position={[0.303, 0.127, -12.429]}
        />
        <mesh
          geometry={nodes.Cube012.geometry}
          material={materials["POLE Metal"]}
          position={[102.977, -0.482, -50.627]}
          scale={[0.213, 0.483, 43.135]}
        />
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials["POLE Metal"]}
          position={[-3.095, -0.482, -50.627]}
          scale={[0.213, 0.483, 43.135]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials["POLE Metal"]}
          position={[96.827, 40.848, -50.627]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[40.96, 1.168, 0.651]}
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials["POLE Metal"]}
          position={[-1.084, 40.207, -50.627]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[40.96, 2.112, 0.651]}
        />
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials["POLE Metal"]}
          position={[101.332, 40.207, -50.627]}
          rotation={[0, 1.571, 0]}
          scale={[40.96, 2.112, 0.651]}
        />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials["POLE Metal"]}
          position={[50.001, 40.236, -50.113]}
          scale={[49.611, 2.076, 0.749]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials["POLE Metal"]}
          position={[50.001, 40.236, -12.403]}
          scale={[49.611, 2.076, 0.749]}
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials["POLE Metal"]}
          position={[50.001, 40.236, -88.645]}
          scale={[49.611, 2.076, 0.749]}
        />
        <mesh
          geometry={nodes.Cube006_Cube001.geometry}
          material={materials["slim spices"]}
          position={[31.252, 12.067, -50.387]}
          rotation={[0, 1.527, 0]}
          scale={0.008}
        />
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials["POLE Metal"]}
          position={[49.944, 19.116, -12.433]}
          scale={[0.529, 19.08, 1.348]}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials["POLE Metal"]}
          position={[99.916, 19.116, -12.433]}
          scale={[0.529, 19.08, 1.348]}
        />
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["POLE Metal"]}
          position={[49.944, 19.116, -88.628]}
          scale={[0.529, 19.08, 1.348]}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["POLE Metal"]}
          position={[0.321, 19.116, -88.628]}
          scale={[0.529, 19.08, 1.348]}
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["POLE Metal"]}
          position={[99.916, 19.116, -88.628]}
          scale={[0.529, 19.08, 1.348]}
        />
        <mesh
          geometry={nodes.Glass5136.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[22.594, 13.638, -45.862]}
          scale={0.025}
        />
        <mesh
          geometry={nodes.Glass010.geometry}
          material={materials["LEATHER.001"]}
          position={[39.12, 13.638, -46.209]}
          scale={0.025}
        />
        <mesh
          geometry={nodes.Glass009.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[47.396, 13.638, -53.388]}
          scale={0.025}
        />
        <mesh
          geometry={nodes.Glass008.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[40.776, 13.638, -55.602]}
          scale={0.025}
        />
        <mesh
          geometry={nodes.Glass007.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[29.575, 13.638, -55.602]}
          scale={0.025}
        />
        <mesh
          geometry={nodes.Glass006.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[16.126, 13.638, -47.712]}
          scale={0.025}
        />
        <mesh
          geometry={nodes.Plate4679.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[13.801, 12.239, -50.436]}
          scale={0.014}
        />
        <mesh
          geometry={nodes.Plate005.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[49.22, 12.239, -50.436]}
          scale={0.014}
        />
        <mesh
          geometry={nodes.Plate004.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[36.808, 12.239, -44.181]}
          scale={0.014}
        />
        <mesh
          geometry={nodes.Plate003.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[37.137, 12.239, -56.939]}
          scale={0.014}
        />
        <mesh
          geometry={nodes.Plate002.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[25.915, 12.239, -56.815]}
          rotation={[0, -0.534, 0]}
          scale={0.014}
        />
        <mesh
          geometry={nodes.plate.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[25.784, 12.239, -44.436]}
          scale={0.014}
        />
        <mesh
          geometry={nodes.Fork4211.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[23.026, 12.193, -44.267]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={1.591}
        />
        <mesh
          geometry={nodes.Fork019.geometry}
          material={materials["LEATHER.001"]}
          position={[49.313, 12.193, -47.715]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={1.591}
        />
        <mesh
          geometry={nodes.Fork017.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[13.944, 12.193, -53.146]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.591}
        />
        <mesh
          geometry={nodes.Fork015.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[39.878, 12.193, -56.672]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={1.591}
        />
        <mesh
          geometry={nodes.Fork013.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[28.681, 12.193, -56.672]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={1.591}
        />
        <mesh
          geometry={nodes.Fork011.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[34.112, 12.193, -44.267]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={1.591}
        />
        <mesh
          geometry={nodes.Knife3980.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[28.457, 12.196, -44.065]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.Knife020.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[49.514, 12.196, -53.146]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.Knife018.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[13.742, 12.196, -47.715]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.Knife016.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[34.447, 12.196, -56.874]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.Knife014.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[23.25, 12.196, -56.874]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.Knife012.geometry}
          material={materials["PLATE KNIFE FOK Glass"]}
          position={[39.543, 12.196, -44.065]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={0.016}
        />
        <mesh
          geometry={nodes.POT.geometry}
          material={materials.pot}
          position={[27.645, 12.153, -50.825]}
          scale={0.022}
        />
      </Center>
    </group>
  );
}

useGLTF.preload("/3D/outdoor-sitting.glb");
